[package]
name = "ytdlp_bindings"
description = "ytdlp cli bindings"
authors = ["c12i <hello@c12i.xyz>"]
version = "0.1.0"
edition = "2021"
license = "MIT"
categories = ["asynchronous"]

[lib]
name = "ytdlp_bindings"
path = "./src/lib.rs"

[dependencies]
anyhow = "1.0.89"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
webvtt-parser = { version = "1.0.0-beta.1", optional = true }
which = "8.0.0"

[build-dependencies]
reqwest = { version = "0.12", features = ["blocking"] }

[dev-dependencies]
glob = "0.3.1"
tempfile = "3.12.0"

[features]
default = [
  "yt-dlp-vendored",
  "audio-processing",
  "video-processing",
  "vtt-processing",
]
yt-dlp-vendored = []
audio-processing = []
video-processing = []
vtt-processing = ["dep:webvtt-parser"]
